source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

pod 'AFNetworking', '~> 1.3.4'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'MJRefresh', '~> 2.4.10'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'DZNEmptyDataSet', '~> 1.5.1'
pod 'AsyncDisplayKit', '~> 1.2.3'
pod 'IQKeyboardManager', '~> 3.2.0.3'
pod 'FMDB'
pod 'SDWebImage', '~> 3.7.1'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 0.6.3'
pod 'ChameleonFramework'
pod 'Mantle', '~> 1.5.6'
pod 'OHHTTPStubs', '~> 4.3.0'
pod 'CocoaLumberjack', '~> 2.0.3'
pod 'ISO8601DateFormatter', '~> 0.7'
pod 'SSKeychain', '~> 1.2.2'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'FormatterKit', '~> 1.8.0'
pod 'Ono', '~> 1.2.0'
#pod 'UMengSocial', '~> 4.2.2'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'DTCoreText', '~> 1.6.15'
pod 'GPUImage', '~> 0.1.7'
pod 'Reveal-iOS-SDK', '~> 1.6.0'
pod 'Appirater'
pod 'OcticonsIOS', :git => 'https://github.com/jacksonh/OcticonsIOS.git', :commit => '4bd3b21'
#pod 'OctoKit', '~> 0.5'
#pod 'evernote-cloud-sdk-ios', :git => 'https://github.com/evernote/evernote-cloud-sdk-ios.git', :branch => 'ios7'
