source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.6.0'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'MJRefresh', '~> 2.4.10'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'DZNEmptyDataSet', '~> 1.7.2'
pod 'AsyncDisplayKit', '~> 1.2.3'
pod 'IQKeyboardManager', '~> 3.3.2'
pod 'FMDB', '~> 2.5'
pod 'SDWebImage', '~> 3.7.3'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'ChameleonFramework'